// Relationships across different files
Ref: Users.badge_level > BadgeLevels.level [delete: set default]
Ref: Users.subscription_id > Subscriptions.id [delete: set null]

Ref: Payments.user_id > Users.id [delete: restrict]
Ref: Payments.processed_by_admin > Users.id [delete: set null]

Ref: Posts.user_id > Users.id
Ref: Posts.deleted_by > Users.id

Ref: Comments.user_id > Users.id
Ref: Comments.deleted_by > Users.id

Ref: PostLikes.user_id > Users.id [delete: cascade]
Ref: PostViews.user_id > Users.id [delete: set null]

Ref: PostMediaMap.media_id > Media.id [delete: cascade]

Ref: ModerationLogs.performed_by > Users.id

Ref: UserTestScores.user_id > Users.id [delete: cascade]

Ref: UserTestAttempts.user_id > Users.id [delete: cascade]

Ref: Notebooks.user_id > Users.id [delete: cascade]

Ref: AILessons.user_id > Users.id [delete: cascade]

Ref: MockTests.created_by > Users.id [delete: set null]
Ref: Tips.created_by > Users.id [delete: set null]
Ref: Media.uploaded_by > Users.id [delete: set null]

Ref: Notifications.recipient_id > Users.id [delete: set null]

Ref: Reports.reporter_id > Users.id [delete: set null]
Ref: Reports.assigned_to > Users.id [delete: set null]
Ref: Reports.resolved_by > Users.id [delete: set null]

Ref: TranslationHistory.user_id > Users.id [delete: cascade]

Ref: UserUsage.user_id > Users.id [delete: cascade]

Ref: MockTestQuestions.media_id > Media.id [delete: set null]