import { MockTestTemplate } from '../../../../types/mocktest';

export const mockD4Template: MockTestTemplate = {
  id: 'cc56d8e9-4f9d-7gff-e1b4-445fdghe443e',
  type: 'D4',
  level: 'Level 4',
  name: 'D4 Level 4 - Template chuẩn',
  description: 'Template khung cho đề thi D4 Level 4 gồm 3 phần: Nghe (25 câu), Đọc (25 câu), và Viết (2 bài).',
  is_active: true,
  created_at: '2025-10-09T12:00:00Z',
  updated_at: '2025-10-09T12:00:00Z',
  structure: {
    total_time_limit: 120,
    total_max_score: 300,
    sections: [
      {
        id: 'listening',
        name: 'Nghe hiểu',
        order_no: 1,
        time_limit: 40,
        max_score: 100,
        total_questions: 25,
        description: 'Kiểm tra khả năng nghe hiểu theo chuẩn D4.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Nghe từ vựng',
            question_type: 'mcq_image',
            question_count: 8,
            options_count: 4,
            input_type: 'audio + image',
            allowed_fields: {
              text: false,
              audio: true,
              images: true,
              explanation: true,
            },
            notes: 'Nghe từ vựng, chọn hình ảnh phù hợp.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Nghe hội thoại',
            question_type: 'mcq_text',
            question_count: 12,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe hội thoại, trả lời câu hỏi.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Nghe bài giảng',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 4,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe bài giảng, hiểu nội dung chính.',
          },
        ],
      },
      {
        id: 'reading',
        name: 'Đọc hiểu',
        order_no: 2,
        time_limit: 50,
        max_score: 100,
        total_questions: 25,
        description: 'Kiểm tra khả năng đọc hiểu văn bản chuyên sâu.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Ngữ pháp và từ vựng',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 4,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Kiểm tra kiến thức ngữ pháp và từ vựng nâng cao.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Đọc hiểu văn bản',
            question_type: 'mcq_text',
            question_count: 15,
            options_count: 4,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc văn bản và phân tích nội dung.',
          },
        ],
      },
      {
        id: 'writing',
        name: 'Viết',
        order_no: 3,
        time_limit: 30,
        max_score: 100,
        total_questions: 2,
        description: 'Kiểm tra khả năng viết tiếng Trung.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Viết đoạn văn ngắn',
            question_type: 'essay',
            question_count: 1,
            options_count: 0,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: true,
              explanation: true,
            },
            notes: 'Viết đoạn văn ngắn theo chủ đề cho sẵn (80-120 từ).',
          },
          {
            part_no: 2,
            title: 'Phần 2: Viết luận',
            question_type: 'essay',
            question_count: 1,
            options_count: 0,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Viết bài luận theo chủ đề (200-300 từ).',
          },
        ],
      },
    ],
  },
};