import { MockTestTemplate } from '../../../../types/mocktest';

export const mockHSK1Template: MockTestTemplate = {
  id: '8d89e0b3-1b6a-49bb-b8e1-112cafe3110b',
  type: 'HSK',
  level: 'HSK1',
  name: 'HSK1 Chuẩn - Template cấu trúc',
  description:
    'Template khung cho đề thi HSK1 gồm 2 phần chính: Nghe hiểu (20 câu, 20 phút) và Đọc hiểu (20 câu, 20 phút). Mỗi phần chia thành 4 nhóm câu hỏi nhỏ với dạng khác nhau.',
  is_active: true,
  created_at: '2025-10-09T10:00:00Z',
  updated_at: '2025-10-09T10:00:00Z',
  structure: {
    total_time_limit: 40,
    total_max_score: 200,
    sections: [
      {
        id: 'listening',
        name: 'Nghe hiểu',
        order_no: 1,
        time_limit: 20,
        max_score: 100,
        total_questions: 20,
        description: 'Kiểm tra khả năng nghe và hiểu tiếng Trung cơ bản.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Nghe chọn hình đúng',
            question_type: 'mcq_image',
            question_count: 5,
            options_count: 3,
            input_type: 'audio + image',
            allowed_fields: {
              text: false,
              audio: true,
              images: true,
              explanation: true,
            },
            notes: 'Mỗi câu có 1 file audio và 3 hình ảnh, chọn hình đúng.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Nghe - Đúng/Sai',
            question_type: 'true_false',
            question_count: 5,
            options_count: 2,
            input_type: 'audio',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe hội thoại ngắn, chọn đúng hoặc sai.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Nghe chọn đáp án đúng',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe câu hỏi, chọn đáp án đúng trong 3 lựa chọn chữ.',
          },
          {
            part_no: 4,
            title: 'Phần 4: Nghe hội thoại - chọn đáp án đúng',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe đoạn hội thoại ngắn, chọn đáp án phù hợp.',
          },
        ],
      },
      {
        id: 'reading',
        name: 'Đọc hiểu',
        order_no: 2,
        time_limit: 20,
        max_score: 100,
        total_questions: 20,
        description: 'Kiểm tra khả năng đọc câu và đoạn văn ngắn.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Ghép câu với hình',
            question_type: 'match_image',
            question_count: 5,
            options_count: 3,
            input_type: 'text + image',
            allowed_fields: {
              text: true,
              audio: false,
              images: true,
              explanation: true,
            },
            notes: 'Đọc câu, chọn hình phù hợp.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Ghép câu hỏi với đáp án',
            question_type: 'pair',
            question_count: 5,
            options_count: 4,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Ghép câu hỏi và đáp án đúng.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Chọn câu hoàn chỉnh',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Chọn câu đúng ngữ pháp.',
          },
          {
            part_no: 4,
            title: 'Phần 4: Đọc đoạn văn - chọn đáp án đúng',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc đoạn ngắn và chọn đáp án đúng.',
          },
        ],
      },
    ],
  },
};