import { MockTestTemplate } from '../../../../types/mocktest';

export const mockHSK2Template: MockTestTemplate = {
  id: '7c78d1a2-0a6a-48aa-a7d0-001abd2200a',
  type: 'HSK',
  level: 'HSK2',
  name: 'HSK2 Chuẩn - Template cấu trúc',
  description: 'Template khung cho đề thi HSK2 gồm 2 phần chính: Nghe hiểu (35 câu, 25 phút) và Đọc hiểu (25 câu, 22 phút).',
  is_active: true,
  created_at: '2025-10-09T10:15:00Z',
  updated_at: '2025-10-09T10:15:00Z',
  structure: {
    total_time_limit: 47,
    total_max_score: 200,
    sections: [
      {
        id: 'listening',
        name: 'Nghe hiểu',
        order_no: 1,
        time_limit: 25,
        max_score: 100,
        total_questions: 35,
        description: 'Kiểm tra khả năng nghe và hiểu tiếng Trung cơ bản.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Nghe chọn hình đúng',
            question_type: 'mcq_image',
            question_count: 10,
            options_count: 4,
            input_type: 'audio + image',
            allowed_fields: {
              text: false,
              audio: true,
              images: true,
              explanation: true,
            },
            notes: 'Nghe từ vựng, chọn hình ảnh phù hợp.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Nghe - Đúng/Sai',
            question_type: 'true_false',
            question_count: 10,
            options_count: 2,
            input_type: 'audio',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe câu, xác định đúng hay sai.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Nghe hội thoại - trắc nghiệm',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe hội thoại, chọn đáp án đúng.',
          },
          {
            part_no: 4,
            title: 'Phần 4: Nghe đoạn văn ngắn',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe đoạn văn và trả lời câu hỏi.',
          },
        ],
      },
      {
        id: 'reading',
        name: 'Đọc hiểu',
        order_no: 2,
        time_limit: 22,
        max_score: 100,
        total_questions: 25,
        description: 'Kiểm tra khả năng đọc hiểu văn bản tiếng Trung.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Ghép câu với hình',
            question_type: 'match_image',
            question_count: 5,
            options_count: 5,
            input_type: 'text + image',
            allowed_fields: {
              text: true,
              audio: false,
              images: true,
              explanation: true,
            },
            notes: 'Ghép câu với hình ảnh tương ứng.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Chọn từ đúng',
            question_type: 'mcq_text',
            question_count: 5,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Chọn từ phù hợp nhất cho câu.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Ghép câu hỏi với đáp án',
            question_type: 'pair',
            question_count: 5,
            options_count: 5,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Ghép câu hỏi với đáp án phù hợp.',
          },
          {
            part_no: 4,
            title: 'Phần 4: Đọc đoạn văn - trả lời câu hỏi',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc đoạn văn và chọn đáp án đúng.',
          },
        ],
      },
    ],
  },
};