import { MockTestTemplate } from '../../../../types/mocktest';

export const mockHSK3Template: MockTestTemplate = {
  id: '9a78f2c4-2c7b-5add-c9f2-223dbfe4221c',
  type: 'HSK',
  level: 'HSK3',
  name: 'HSK3 Chuẩn - Template đầy đủ',
  description: 'Template khung cho đề thi HSK3 gồm 3 phần: Nghe hiểu (40 câu, 35 phút), Đọc hiểu (30 câu, 30 phút), và Viết (10 câu, 15 phút).',
  is_active: true,
  created_at: '2025-10-09T10:30:00Z',
  updated_at: '2025-10-09T10:30:00Z',
  structure: {
    total_time_limit: 80,
    total_max_score: 300,
    sections: [
      {
        id: 'listening',
        name: 'Nghe hiểu',
        order_no: 1,
        time_limit: 35,
        max_score: 100,
        total_questions: 40,
        description: 'Kiểm tra khả năng nghe và hiểu tiếng Trung trình độ trung cấp thấp.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Nghe chọn hình đúng',
            question_type: 'mcq_image',
            question_count: 10,
            options_count: 4,
            input_type: 'audio + image',
            allowed_fields: {
              text: false,
              audio: true,
              images: true,
              explanation: true,
            },
            notes: 'Nghe câu, chọn hình ảnh phù hợp nhất trong 4 lựa chọn.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Nghe hội thoại ngắn',
            question_type: 'true_false',
            question_count: 10,
            options_count: 2,
            input_type: 'audio',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe hội thoại, xác định câu phát biểu đúng hay sai.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Nghe hội thoại - trắc nghiệm',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe hội thoại, chọn đáp án đúng nhất.',
          },
          {
            part_no: 4,
            title: 'Phần 4: Nghe đoạn văn dài',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe đoạn văn và trả lời câu hỏi.',
          },
        ],
      },
      {
        id: 'reading',
        name: 'Đọc hiểu',
        order_no: 2,
        time_limit: 30,
        max_score: 100,
        total_questions: 30,
        description: 'Kiểm tra khả năng đọc hiểu văn bản tiếng Trung.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Ghép từ với định nghĩa',
            question_type: 'pair',
            question_count: 10,
            options_count: 5,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Ghép từ vựng với định nghĩa hoặc nghĩa phù hợp.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Điền từ vào chỗ trống',
            question_type: 'fill_blank',
            question_count: 10,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Chọn từ phù hợp để điền vào chỗ trống trong câu.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Đọc đoạn văn - trả lời câu hỏi',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc đoạn văn và chọn đáp án đúng cho câu hỏi.',
          },
        ],
      },
      {
        id: 'writing',
        name: 'Viết',
        order_no: 3,
        time_limit: 15,
        max_score: 100,
        total_questions: 10,
        description: 'Kiểm tra khả năng viết câu và đoạn văn tiếng Trung.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Sắp xếp từ thành câu',
            question_type: 'fill_blank',
            question_count: 5,
            options_count: 1,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Sắp xếp các từ cho sẵn thành câu có nghĩa.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Viết câu theo hình ảnh',
            question_type: 'essay',
            question_count: 5,
            options_count: 1,
            input_type: 'text + image',
            allowed_fields: {
              text: true,
              audio: false,
              images: true,
              explanation: true,
            },
            notes: 'Viết câu mô tả hình ảnh hoặc tình huống.',
          },
        ],
      },
    ],
  },
};