import { MockTestTemplate } from '../../../../types/mocktest';

export const mockHSKKBasicTemplate: MockTestTemplate = {
  id: 'dd67e9fa-5g0e-8hgg-f2c5-556geihf554f',
  type: 'HSKK',
  level: 'Basic',
  name: 'HSKK Basic - Template chuẩn',
  description: 'Template khung cho đề thi HSKK Basic gồm 3 phần: Lặp lại (27 câu), Đọc to (10 câu), và Trả lời câu hỏi (2 câu).',
  is_active: true,
  created_at: '2025-10-09T13:00:00Z',
  updated_at: '2025-10-09T13:00:00Z',
  structure: {
    total_time_limit: 25,
    total_max_score: 200,
    sections: [
      {
        id: 'repeat',
        name: 'Lặp lại',
        order_no: 1,
        time_limit: 7,
        max_score: 80,
        total_questions: 27,
        description: 'Nghe và lặp lại các từ, cụm từ và câu.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Lặp lại từ đơn',
            question_type: 'essay',
            question_count: 15,
            options_count: 0,
            input_type: 'audio',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe và lặp lại từ đơn (ghi âm phản hồi).',
          },
          {
            part_no: 2,
            title: 'Phần 2: Lặp lại câu ngắn',
            question_type: 'essay',
            question_count: 12,
            options_count: 0,
            input_type: 'audio',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe và lặp lại câu ngắn (ghi âm phản hồi).',
          },
        ],
      },
      {
        id: 'read_aloud',
        name: 'Đọc to',
        order_no: 2,
        time_limit: 8,
        max_score: 60,
        total_questions: 10,
        description: 'Đọc to các từ và câu được hiển thị.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Đọc từ vựng',
            question_type: 'essay',
            question_count: 5,
            options_count: 0,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc to từ vựng hiển thị trên màn hình (ghi âm).',
          },
          {
            part_no: 2,
            title: 'Phần 2: Đọc câu',
            question_type: 'essay',
            question_count: 5,
            options_count: 0,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc to các câu hiển thị trên màn hình (ghi âm).',
          },
        ],
      },
      {
        id: 'answer_questions',
        name: 'Trả lời câu hỏi',
        order_no: 3,
        time_limit: 10,
        max_score: 60,
        total_questions: 2,
        description: 'Trả lời câu hỏi bằng lời nói.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Trả lời câu hỏi đơn giản',
            question_type: 'essay',
            question_count: 2,
            options_count: 0,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: true,
              explanation: true,
            },
            notes: 'Trả lời câu hỏi đơn giản bằng tiếng Trung (ghi âm).',
          },
        ],
      },
    ],
  },
};