import { MockTestTemplate } from '../../../../types/mocktest';

export const mockTOCFLBandATemplate: MockTestTemplate = {
  id: 'bb45c7d8-3e8c-6fee-d0a3-334ecgf5332d',
  type: 'TOCFL',
  level: 'Band A',
  name: 'TOCFL Band A - Template chuẩn',
  description: 'Template khung cho đề thi TOCFL Band A gồm 3 phần: Nghe (35 câu), Đọc (40 câu), và Khẩu ngữ (27 câu).',
  is_active: true,
  created_at: '2025-10-09T11:00:00Z',
  updated_at: '2025-10-09T11:00:00Z',
  structure: {
    total_time_limit: 110,
    total_max_score: 400,
    sections: [
      {
        id: 'listening',
        name: 'Nghe hiểu',
        order_no: 1,
        time_limit: 60,
        max_score: 120,
        total_questions: 35,
        description: 'Kiểm tra khả năng nghe hiểu tiếng Trung theo chuẩn TOCFL.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Nghe từ vựng cơ bản',
            question_type: 'mcq_text',
            question_count: 15,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe từ vựng, chọn nghĩa đúng.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Nghe hội thoại ngắn',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe hội thoại, trả lời câu hỏi.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Nghe đoạn văn',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 3,
            input_type: 'audio + text',
            allowed_fields: {
              text: false,
              audio: true,
              images: false,
              explanation: true,
            },
            notes: 'Nghe đoạn văn và trả lời câu hỏi chi tiết.',
          },
        ],
      },
      {
        id: 'reading',
        name: 'Đọc hiểu',
        order_no: 2,
        time_limit: 50,
        max_score: 160,
        total_questions: 40,
        description: 'Kiểm tra khả năng đọc hiểu văn bản tiếng Trung.',
        parts: [
          {
            part_no: 1,
            title: 'Phần 1: Từ vựng và ngữ pháp',
            question_type: 'mcq_text',
            question_count: 15,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Chọn từ hoặc cấu trúc ngữ pháp phù hợp.',
          },
          {
            part_no: 2,
            title: 'Phần 2: Đọc hiểu đoạn văn ngắn',
            question_type: 'mcq_text',
            question_count: 15,
            options_count: 3,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc đoạn văn ngắn, trả lời câu hỏi.',
          },
          {
            part_no: 3,
            title: 'Phần 3: Đọc hiểu đoạn văn dài',
            question_type: 'mcq_text',
            question_count: 10,
            options_count: 4,
            input_type: 'text',
            allowed_fields: {
              text: true,
              audio: false,
              images: false,
              explanation: true,
            },
            notes: 'Đọc đoạn văn dài, phân tích nội dung.',
          },
        ],
      },
    ],
  },
};